language: python
# PIP is a package manager for Python packages and/or modules.
cache: pip

python:
  - 3.7.2
  
env:
  - DJANGO_VERSION==2.1.9

dist:
  - xenial

install:
- pip install -r requirements.txt
  
services:
  - db.sqlite3

before_script:
  - touch travis_ci_db # creates a new file called `travis_ci_db`. SQLite databases can be created as simple flat files
  - python manage.py migrate

# command to run tests
script:
  - python manage.py test
